name: EasyCrypt Unit Examples Compilation

on: [push,pull_request]

env:
  HOME: /home/charlie
  OPAMYES: true
  OPAMJOBS: 2

jobs:
  check-unit-examples:
    name: Check Unit Examples
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/easycrypt/ec-build-box
    steps:
    - uses: actions/checkout@v4
    - name: Install EasyCrypt
      run: |
        opam pin add -n easycrypt git+https://github.com/EasyCrypt/easycrypt
        opam install easycrypt
    - name: Detect SMT provers
      run: |
        opam exec -- easycrypt why3config
    - name: Check Unit Tests
      run: |
        opam exec -- easycrypt runtest config/tests.config units

  generate-pages:
    name: Generate GitHub Pages
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/easycrypt/ec-build-box
    steps:
    - uses: actions/checkout@v4
    - name: Install pandoc
      run: |
        sudo apt-get install -y pandoc
        pip3 install --user --break-system-packages panflute
    - name: Run pandoc & generate pages
      run: |
        make pages
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v3
    - name: Upload Artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v1
      with:
        path: "./_pages"

  deploy-pages:
    if: github.ref == 'refs/heads/main'
    needs: [generate-pages]
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
